package upeu.edu.pe.model.entity;
// Generated 23/10/2016 05:03:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Asistente generated by hbm2java
 */
@Entity
public class Asistente  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
     private Integer idasistente;
     private String voucher;
     private String operacion;
     private Date fecha;
     private String carne;
     private String nombres;
     @Column(name = "apellido_pat")
     private String apellidoPat;
     @Column(name = "apellido_mat")
     private String apellidoMat;
     private String dni;
     private String ep;
     private Double importe;
     private Integer evento;
     
    public Asistente() {
    }

    public Asistente(Integer idasistente, String voucher, String operacion, Date fecha, String carne, String nombres, String apellidoPat, String apellidoMat, String dni, String ep, Double importe, Integer evento) {
        this.idasistente = idasistente;
        this.voucher = voucher;
        this.operacion = operacion;
        this.fecha = fecha;
        this.carne = carne;
        this.nombres = nombres;
        this.apellidoPat = apellidoPat;
        this.apellidoMat = apellidoMat;
        this.dni = dni;
        this.ep = ep;
        this.importe = importe;
        this.evento = evento;
    }

    public Integer getIdasistente() {
        return idasistente;
    }

    public void setIdasistente(Integer idasistente) {
        this.idasistente = idasistente;
    }

    public String getVoucher() {
        return voucher;
    }

    public void setVoucher(String voucher) {
        this.voucher = voucher;
    }

    public String getOperacion() {
        return operacion;
    }

    public void setOperacion(String operacion) {
        this.operacion = operacion;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getCarne() {
        return carne;
    }

    public void setCarne(String carne) {
        this.carne = carne;
    }

    public String getNombres() {
        return nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    public String getApellidoPat() {
        return apellidoPat;
    }

    public void setApellidoPat(String apellidoPat) {
        this.apellidoPat = apellidoPat;
    }

    public String getApellidoMat() {
        return apellidoMat;
    }

    public void setApellidoMat(String apellidoMat) {
        this.apellidoMat = apellidoMat;
    }

    public String getDni() {
        return dni;
    }

    public void setDni(String dni) {
        this.dni = dni;
    }

    public String getEp() {
        return ep;
    }

    public void setEp(String ep) {
        this.ep = ep;
    }

    public Double getImporte() {
        return importe;
    }

    public void setImporte(Double importe) {
        this.importe = importe;
    }

    public Integer getIdevento() {
        return evento;
    }

    public void setIdevento(Integer idevento) {
        this.evento = idevento;
    }

    
    
}


