package upeu.edu.pe.model.entity;
// Generated 23/10/2016 05:03:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Evento generated by hbm2java
 */
@Entity
public class Evento  implements java.io.Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
     private Integer idevento;
     private Integer idorganizador;
     private String evento;
     @Column(name = "fecha_inicio")
     private Date fechaInicio;
     @Column(name = "fecha_fin")
     private Date fechaFin;

    public Evento() {
    }


    public Evento(Integer idorganizador, String evento, Date fechaInicio, Date fechaFin) {
        this.idorganizador = idorganizador;
       this.evento = evento;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public Integer getIdevento() {
        return this.idevento;
    }
    
    public void setIdevento(Integer idevento) {
        this.idevento = idevento;
    }
    public String getEvento() {
        return this.evento;
    }
    
    public void setEvento(String evento) {
        this.evento = evento;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }


}


