package upeu.edu.pe.model.entity;
// Generated 23/10/2016 05:03:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EventoSesion generated by hbm2java
 */
@Entity
@Table(name = "evento_sesion")
public class EventoSesion  implements java.io.Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "idevento_sesion")
     private Integer ideventoSesion;     
     private Integer idevento;
     private String sesion;
     private Date fecha;
     private Date hora;
     private String descripcion;
     private Character estado;

    public EventoSesion() {
    }

    public EventoSesion(Integer ideventoSesion, Integer idevento, String sesion, Date fecha, Date hora, String descripcion, Character estado) {
        this.ideventoSesion = ideventoSesion;
        this.idevento = idevento;
        this.sesion = sesion;
        this.fecha = fecha;
        this.hora = hora;
        this.descripcion = descripcion;
        this.estado = estado;
    }
   
    
   
    public Integer getIdeventoSesion() {
        return this.ideventoSesion;
    }
    
    public void setIdeventoSesion(Integer ideventoSesion) {
        this.ideventoSesion = ideventoSesion;
    }
    public String getSesion() {
        return this.sesion;
    }
    
    public void setSesion(String sesion) {
        this.sesion = sesion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }

    public Integer getIdevento() {
        return idevento;
    }

    public void setIdevento(Integer idevento) {
        this.idevento = idevento;
    }


}


