package upeu.edu.pe.model.entity;
// Generated 23/10/2016 05:03:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Organizador generated by hbm2java
 */
@Entity
public class Organizador  implements java.io.Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
     private Integer idorganizador;
     private String organizador;
     private String responzable;

    public Organizador() {
    }

    public Organizador(String organizador, String responzable) {
       this.organizador = organizador;
       this.responzable = responzable;
    }
   
    public Integer getIdorganizador() {
        return this.idorganizador;
    }
    
    public void setIdorganizador(Integer idorganizador) {
        this.idorganizador = idorganizador;
    }
    public String getOrganizador() {
        return this.organizador;
    }
    
    public void setOrganizador(String organizador) {
        this.organizador = organizador;
    }
    public String getResponzable() {
        return this.responzable;
    }
    
    public void setResponzable(String responzable) {
        this.responzable = responzable;
    }


}


