package upeu.edu.pe.model.entity;
// Generated 23/10/2016 05:03:24 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;




/**
 * Usuario generated by hbm2java
 */
@Entity
public class Usuario  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
     private Integer idusuario;
     private Integer idevento;
     private String usuario;
     private String clave;
     private String rol;

    public Usuario() {
    }

    public Usuario(Integer idusuario, Integer idevento, String usuario, String clave, String rol) {
        this.idusuario = idusuario;
        this.idevento = idevento;
        this.usuario = usuario;
        this.clave = clave;
        this.rol = rol;
    }

    
   
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }

    public Integer getIdevento() {
        return idevento;
    }

    public void setIdevento(Integer idevento) {
        this.idevento = idevento;
    }




}


